### ISSUE TITLE
Какой URL для открытия WEB интерфейса?

### ISSUE THREAD

**Issue by g1ibby** [powerman/tr#1]
``http://127.0.0.1:8844/`` на этой странице выводит ``404 page not found`` на черном фоне. 

Давно искал что то подобное, очень рад что ты написал. Спасибо!

**Comment by powerman** [comment]
О, точно, надо инструкции обновить. Забыл написать там, что сначала проект собрать надо: запусти `./scripts/build`. wasm он же как обычный гошный бинарник - весит мегабайты, его в репо класть нет смысла.

**Comment by powerman** [comment]
Ну или ./script/build-web, для сборки только фронтовой части хватит и его.
